const API={score:'https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard',all:'https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates=20260611-20260719&limit=300',ko:'https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard?dates=20260627-20260720&limit=300',stand:'https://site.web.api.espn.com/apis/v2/sports/soccer/fifa.world/standings'};
const app=document.querySelector('#app');
const LS='wc26-hub-fav';
let state={data:null,filter:'live',q:'',fav:localStorage.getItem(LS)||'',err:null};
const fmtTime=new Intl.DateTimeFormat('tr-TR',{hour:'2-digit',minute:'2-digit'});
const fmtDate=new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const flags={argentina:'ar',australia:'au',austria:'at',belgium:'be',brazil:'br',canada:'ca',croatia:'hr',colombia:'co',egypt:'eg',england:'gb-eng',france:'fr',germany:'de',ghana:'gh',japan:'jp',mexico:'mx',morocco:'ma',netherlands:'nl',norway:'no',paraguay:'py',portugal:'pt',senegal:'sn',spain:'es',sweden:'se',switzerland:'ch',algeria:'dz','south africa':'za','ivory coast':'ci','cote d ivoire':'ci','united states':'us',usa:'us','dr congo':'cd','bosnia and herzegovina':'ba','cape verde':'cv','cabo verde':'cv',ecuador:'ec'};
function flag(t){let n=norm(t.name);let code=flags[n]||Object.entries(flags).find(([k])=>n.includes(k))?.[1];let src=code?`https://flagcdn.com/w80/${code}.png`:t.logo;return `<span class="flag">${src?`<img src="${esc(src)}" alt="">`:esc((t.abbr||t.name||'?').slice(0,2))}</span>`}
function team(x){return {id:x?.id,name:x?.displayName||x?.shortDisplayName||x?.location||x?.name||'Takım',abbr:x?.abbreviation||'',logo:x?.logo||x?.logos?.[0]?.href||''}}
function parseGroup(v){let m=String(v||'').match(/group\s+([A-L])/i)||String(v||'').match(/\b([A-L])\b/);return m?m[1].toUpperCase():String(v||'')}
function parseMatches(payloads){let map=new Map();payloads.forEach(p=>(p?.events||[]).forEach(e=>map.set(e.id,e)));return [...map.values()].map(e=>{let c=e.competitions?.[0],cs=c?.competitors||[],h=cs.find(x=>x.homeAway==='home'),a=cs.find(x=>x.homeAway==='away'),st=c?.status||e.status,kind=st?.type?.state||'pre';if(!c||!h||!a)return null;let details=(c.details||[]).filter(d=>d.scoringPlay||d.type?.text==='Goal').map(d=>({min:d.clock?.displayValue||'',name:d.athletesInvolved?.[0]?.displayName||d.athletesInvolved?.[0]?.shortName||'Gol'}));return {id:e.id,date:e.date||c.date,round:c.altGameNote||e.season?.slug||'',group:parseGroup(c.altGameNote||e.season?.slug),venue:c.venue?.fullName||c.venue?.displayName||'',city:c.venue?.address?.city||'',home:team(h.team),away:team(a.team),hg:h.score===''?null:Number(h.score),ag:a.score===''?null:Number(a.score),hs:h.shootoutScore??null,as:a.shootoutScore??null,hw:h.winner===true,aw:a.winner===true,live:kind==='in',done:kind==='post'||st?.type?.completed,details}}).filter(Boolean).sort((a,b)=>Date.parse(a.date)-Date.parse(b.date))}
function parseStandings(p){return (p.children||[]).map(ch=>{let g=parseGroup(ch.name||ch.abbreviation);let rows=(ch.standings?.entries||[]).map(en=>{let st=n=>(en.stats||[]).find(x=>x.name===n||x.type===n)?.value||0;let gf=st('pointsFor'),ga=st('pointsAgainst');return {rank:st('rank')||en.note?.rank||0,team:team(en.team),p:st('points'),gd:st('pointDifferential')||gf-ga}}).sort((a,b)=>a.rank-b.rank);return {g,rows}}).filter(x=>x.rows.length)}
function roundKey(m){let l=(m.round||m.group||'').toLowerCase();if(l.includes('round of 32'))return'Son 32';if(l.includes('round of 16'))return'Son 16';if(l.includes('quarter'))return'Çeyrek';if(l.includes('semi'))return'Yarı';if(l.includes('final'))return'Final';return /^[A-L]$/.test(m.group)?'Grup '+m.group:(m.round||'Maç')}
async function j(u){let r=await fetch(u+(u.includes('?')?'&':'?')+'_='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Veri alınamadı');return r.json()}
async function load(){try{let [s,a,k,st]=await Promise.all([j(API.score),j(API.all),j(API.ko),j(API.stand)]);let matches=parseMatches([s,a,k]);state.data={matches,groups:parseStandings(st),live:matches.filter(x=>x.live),next:matches.find(x=>!x.done&&!x.live&&Date.parse(x.date)>=Date.now()),updated:new Date().toISOString()};state.err=null}catch(e){state.err=e.message}render()}
function heroMatch(){let d=state.data,m=d.live[0]||d.next;if(!m)return `<div class="empty">Planlanmış maç bulunamadı.</div>`;let live=m.live;return `<div class="focus"><h2>${live?'<span class="live-dot"></span> Canlı Maç':'Sıradaki Maç'}</h2><div class="big-match"><div class="teams"><div class="team">${flag(m.home)}<div>${esc(m.home.name)}</div></div><div class="score">${live||m.done?`${m.hg??'-'} - ${m.ag??'-'}`:'VS'}</div><div class="team">${flag(m.away)}<div>${esc(m.away.name)}</div></div></div><div class="sub">${live?'CANLI':fmtDate.format(new Date(m.date))} · ${esc(roundKey(m))}${m.city?' · '+esc(m.city):''}</div>${m.details?.length?`<div class="sub">${m.details.map(g=>esc(g.min+' '+g.name)).join(' · ')}</div>`:''}</div></div>`}
function metrics(){let ms=state.data.matches,sc=ms.filter(m=>m.live||m.done),goals=sc.reduce((t,m)=>t+(m.hg||0)+(m.ag||0),0);return `<section class="grid"><article class="card"><div class="card-head"><h2>Turnuva</h2><span class="sub">Canlı veri</span></div><div class="card-body metric"><strong>${goals}</strong><span>gol · ${sc.length} maç</span><div class="stat-row"><div class="mini"><b>${state.data.live.length}</b><small>Canlı</small></div><div class="mini"><b>${ms.filter(x=>x.done).length}</b><small>Biten</small></div><div class="mini"><b>${ms.filter(x=>!x.done&&!x.live).length}</b><small>Gelecek</small></div></div></div></article><article class="card"><div class="card-head"><h2>Favori Takım</h2></div><div class="card-body">${favBox()}</div></article><article class="card"><div class="card-head"><h2>Bugün</h2></div><div class="card-body metric"><strong>${ms.filter(m=>day(m.date)===day(new Date())).length}</strong><span>maç</span></div></article><article class="card"><div class="card-head"><h2>Güncelleme</h2></div><div class="card-body metric"><strong style="font-size:34px">${fmtTime.format(new Date(state.data.updated))}</strong><span>10 sn otomatik</span></div></article></section>`}
function day(v){let d=new Date(v);return d.toDateString()}
function favBox(){let teams=[...new Map(state.data.groups.flatMap(g=>g.rows.map(r=>[r.team.name,r.team])).sort()).values()];let sel=state.fav?state.data.matches.filter(m=>norm(m.home.name)===norm(state.fav)||norm(m.away.name)===norm(state.fav)):[];return `<div class="fav-row"><select id="fav"><option value="">Takım seç</option>${teams.map(t=>`<option ${t.name===state.fav?'selected':''}>${esc(t.name)}</option>`).join('')}</select></div>${state.fav?`<p class="sub" style="margin-top:12px">${esc(state.fav)} için ${sel.length} maç bulundu.</p>`:'<p class="sub" style="margin-top:12px">Seçimin bu tarayıcıda saklanır.</p>'}`}
function matchCard(m){let live=m.live;return `<div class="match ${live?'live':''}"><div class="time">${live?'CANLI':m.done?'MS':fmtTime.format(new Date(m.date))}</div><div class="side"><div class="row">${flag(m.home)}<span>${esc(m.home.name)}</span><b>${live||m.done?m.hg??'-':''}</b></div><div class="row">${flag(m.away)}<span>${esc(m.away.name)}</span><b>${live||m.done?m.ag??'-':''}</b></div></div><div class="tag">${esc(roundKey(m))}<br>${esc(m.city)}</div></div>`}
function filtered(){let m=state.data.matches,q=norm(state.q);if(state.filter==='live')m=m.filter(x=>x.live);if(state.filter==='today')m=m.filter(x=>day(x.date)===day(new Date()));if(state.filter==='next')m=m.filter(x=>!x.live&&!x.done);if(state.filter==='done')m=m.filter(x=>x.done).reverse();if(q)m=m.filter(x=>norm(x.home.name).includes(q)||norm(x.away.name).includes(q));return m}
function matches(){let m=filtered();return `<section class="card" id="maclar"><div class="card-head"><h2>Maç Merkezi</h2><span class="sub">${m.length} maç</span></div><div class="tools">${[['live','Canlı'],['today','Bugün'],['next','Gelecek'],['done','Biten'],['all','Tümü']].map(([k,v])=>`<button class="tab ${state.filter===k?'active':''}" data-f="${k}">${v}</button>`).join('')}<input class="search" id="q" placeholder="Takım ara" value="${esc(state.q)}"></div><div class="match-list">${m.length?m.slice(0,80).map(matchCard).join(''):'<div class="empty">Bu filtrede maç yok.</div>'}</div></section>`}
function bracket(){let rounds=['Son 32','Son 16','Çeyrek','Yarı','Final'];return `<section class="card" id="yol"><div class="card-head"><h2>Şampiyonluk Yolu</h2><span class="sub">Yatay kaydır</span></div><div class="bracket">${rounds.map(r=>`<div class="round"><div class="round-title">${r}</div>${state.data.matches.filter(m=>roundKey(m)===r).map(m=>`<div class="tie"><div class="tie-meta"><span>${m.done?'MS':fmtDate.format(new Date(m.date))}</span><span>${esc(m.city)}</span></div><div class="row ${m.hw?'winner':''}">${flag(m.home)}<span>${esc(m.home.name)}</span><b>${m.done||m.live?m.hg??'':''}</b></div><div class="row ${m.aw?'winner':''}">${flag(m.away)}<span>${esc(m.away.name)}</span><b>${m.done||m.live?m.ag??'':''}</b></div></div>`).join('')||'<div class="empty">Bekleniyor</div>'}</div>`).join('')}</div></section>`}
function timeline(){let days=[...new Map(state.data.matches.map(m=>[day(m.date),m])).values()].slice(0,40);return `<section class="card" id="takvim"><div class="card-head"><h2>Takvim Akışı</h2></div><div class="timeline">${days.map(m=>`<div class="day ${day(m.date)===day(new Date())?'today':''}"><b>${fmtDate.format(new Date(m.date))}</b><span class="sub">${state.data.matches.filter(x=>day(x.date)===day(m.date)).length} maç</span></div>`).join('')}</div></section>`}
function groups(){return `<section class="card" id="gruplar"><div class="card-head"><h2>Gruplar</h2></div><div class="groups">${state.data.groups.map(g=>`<article class="group"><h3>${esc(g.g)} Grubu</h3><table>${g.rows.map(r=>`<tr><td>${r.rank}. ${esc(r.team.name)}</td><td>${r.p}</td></tr>`).join('')}</table></article>`).join('')}</div></section>`}
function render(){if(state.err){app.innerHTML=`<section class="loading"><h1>Veri alınamadı</h1><p>${esc(state.err)}</p><button class="btn" onclick="location.reload()">Tekrar dene</button></section>`;return}if(!state.data)return;let live=state.data.live.length;app.innerHTML=`<div class="shell"><header class="top"><div class="bar"><div class="brand"><i></i>WC26 <b>Live Hub</b></div><span class="pill live">${live} canlı</span><div class="top-meta"><span class="hide-sm">Güncellendi ${fmtTime.format(new Date(state.data.updated))}</span><button class="btn ghost" id="theme">Tema</button><button class="btn" id="refresh">Yenile</button></div></div></header><main class="wrap"><section class="hero"><div class="hero-card"><h1>Dünya Kupası kontrol paneli.</h1><p>Canlı maç, fikstür, favori takım, şampiyonluk yolu ve grup tabloları tek ekranda.</p><nav class="quick"><a href="#maclar">Maçlar</a><a href="#yol">Yol</a><a href="#takvim">Takvim</a><a href="#gruplar">Gruplar</a></nav></div>${heroMatch()}</section>${metrics()}<section class="layout"><div>${bracket()}${timeline()}${groups()}</div><aside class="side-panel">${matches()}</aside></section></main><nav class="bottom-nav"><a href="#app">Ana</a><a href="#maclar">Maç</a><a href="#yol">Yol</a><a href="#gruplar">Grup</a></nav></div>`;bind()}
function bind(){document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.f;render()});let q=document.querySelector('#q');if(q)q.oninput=e=>{state.q=e.target.value;render()};let fav=document.querySelector('#fav');if(fav)fav.onchange=e=>{state.fav=e.target.value;localStorage.setItem(LS,state.fav);render()};document.querySelector('#refresh')?.addEventListener('click',load);document.querySelector('#theme')?.addEventListener('click',()=>document.documentElement.style.filter=document.documentElement.style.filter?'':'invert(1) hue-rotate(180deg)')}
load();setInterval(()=>!document.hidden&&load(),10000);document.addEventListener('visibilitychange',()=>!document.hidden&&load());